name: Build, push and deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        working-directory: /api
        run: |
          docker build -t zocomchristoffer/test-api .

      - name: Push Docker image
        run: |
          docker push zocomchristoffer/test-api

      - name: Deploy
        env:
          deploy_url: ${{secrets.RENDER_DEPLOY_URL}}
        run: |
          curl "$deploy_url"
